function config() {

}

//TODO 首页先隐藏(app.json)
/*{
 "pagePath": "pages/info/rcmStory/rcmStory",
 "iconPath": "images/menu/home.png",
 "selectedIconPath": "images/menu/homeHL.png",
 "text": "首页"
 },*/

config.prototype = {
    //本地缓存--key名称
    LSKey: {},
    //api接口url地址集
    apiUrls: {},
    //pages页面跳转
    pages: {},
    cityObj: {
        "topCitys": [{
            "id": 100000,
            "city": "北京市",
            "pinyin": "beijingshi"
        }, {
            "id": 100020,
            "city": "上海市",
            "pinyin": "shanghaishi"
        }, {
            "id": 100190,
            "city": "广州市",
            "pinyin": "guangzhoushi"
        }, {
            "id": 100191,
            "city": "深圳市",
            "pinyin": "shenzhenshi"
        }, {
            "id": 100100,
            "city": "南京市",
            "pinyin": "nanjingshi"
        }, {
            "id": 100170,
            "city": "武汉市",
            "pinyin": "wuhanshi"
        }, {
            "id": 101012,
            "city": "苏州市",
            "pinyin": "suzhoushi"
        }, {
            "id": 100110,
            "city": "杭州市",
            "pinyin": "hangzhoushi"
        }, {
            "id": 100220,
            "city": "成都市",
            "pinyin": "chengdushi"
        }],
        "citys": [{
            "id": 100000,
            "city": "北京市",
            "pinyin": "beijingshi"
        }, {
            "id": 100010,
            "city": "天津市",
            "pinyin": "tianjinshi"
        }, {
            "id": 100020,
            "city": "上海市",
            "pinyin": "shanghaishi"
        }, {
            "id": 100030,
            "city": "重庆市",
            "pinyin": "chongqingshi"
        }, {
            "id": 100040,
            "city": "石家庄市",
            "pinyin": "shijiazhuangshi"
        }, {
            "id": 100041,
            "city": "张家口市",
            "pinyin": "zhangjiakoushi"
        }, {
            "id": 100042,
            "city": "承德市",
            "pinyin": "chengdeshi"
        }, {
            "id": 100043,
            "city": "秦皇岛市",
            "pinyin": "qinhuangdaoshi"
        }, {
            "id": 100044,
            "city": "唐山市",
            "pinyin": "tangshanshi"
        }, {
            "id": 100045,
            "city": "廊坊市",
            "pinyin": "langfangshi"
        }, {
            "id": 100046,
            "city": "保定市",
            "pinyin": "baodingshi"
        }, {
            "id": 100047,
            "city": "衡水市",
            "pinyin": "hengshuishi"
        }, {
            "id": 100048,
            "city": "沧州市",
            "pinyin": "cangzhoushi"
        }, {
            "id": 100049,
            "city": "邢台市",
            "pinyin": "xingtaishi"
        }, {
            "id": 100410,
            "city": "邯郸市",
            "pinyin": "handanshi"
        }, {
            "id": 100050,
            "city": "太原市",
            "pinyin": "taiyuanshi"
        }, {
            "id": 100051,
            "city": "朔州市",
            "pinyin": "shuozhoushi"
        }, {
            "id": 100052,
            "city": "大同市",
            "pinyin": "datongshi"
        }, {
            "id": 100053,
            "city": "阳泉市",
            "pinyin": "yangquanshi"
        }, {
            "id": 100054,
            "city": "长治市",
            "pinyin": "changzhishi"
        }, {
            "id": 100055,
            "city": "晋城市",
            "pinyin": "jinchengshi"
        }, {
            "id": 100056,
            "city": "忻州市",
            "pinyin": "xinzhoushi"
        }, {
            "id": 100057,
            "city": "晋中市",
            "pinyin": "jinzhongshi"
        }, {
            "id": 100058,
            "city": "临汾市",
            "pinyin": "linfenshi"
        }, {
            "id": 100059,
            "city": "吕梁市",
            "pinyin": "lvliangshi"
        }, {
            "id": 100510,
            "city": "运城市",
            "pinyin": "yunchengshi"
        }, {
            "id": 100060,
            "city": "呼和浩特市",
            "pinyin": "huhehaoteshi"
        }, {
            "id": 100061,
            "city": "包头市",
            "pinyin": "baotoushi"
        }, {
            "id": 100062,
            "city": "乌海市",
            "pinyin": "wuhaishi"
        }, {
            "id": 100063,
            "city": "赤峰市",
            "pinyin": "chifengshi"
        }, {
            "id": 100064,
            "city": "通辽市",
            "pinyin": "tongliaoshi"
        }, {
            "id": 100065,
            "city": "呼伦贝尔市",
            "pinyin": "hulunbeiershi"
        }, {
            "id": 100066,
            "city": "鄂尔多斯市",
            "pinyin": "eerduosishi"
        }, {
            "id": 100067,
            "city": "乌兰察布市",
            "pinyin": "wulanchabushi"
        }, {
            "id": 100068,
            "city": "巴彦淖尔市",
            "pinyin": "bayannaoershi"
        }, {
            "id": 100069,
            "city": "兴安盟",
            "pinyin": "xinganmeng"
        }, {
            "id": 100610,
            "city": "锡林郭勒盟",
            "pinyin": "xilinguolemeng"
        }, {
            "id": 100611,
            "city": "阿拉善盟",
            "pinyin": "alashanmeng"
        }, {
            "id": 100070,
            "city": "沈阳市",
            "pinyin": "shenyangshi"
        }, {
            "id": 100071,
            "city": "朝阳市",
            "pinyin": "chaoyangshi"
        }, {
            "id": 100072,
            "city": "阜新市",
            "pinyin": "fuxinshi"
        }, {
            "id": 100073,
            "city": "铁岭市",
            "pinyin": "tielingshi"
        }, {
            "id": 100074,
            "city": "抚顺市",
            "pinyin": "fushunshi"
        }, {
            "id": 100075,
            "city": "本溪市",
            "pinyin": "benxishi"
        }, {
            "id": 100076,
            "city": "辽阳市",
            "pinyin": "liaoyangshi"
        }, {
            "id": 100077,
            "city": "鞍山市",
            "pinyin": "anshanshi"
        }, {
            "id": 100078,
            "city": "丹东市",
            "pinyin": "dandongshi"
        }, {
            "id": 100079,
            "city": "大连市",
            "pinyin": "dalianshi"
        }, {
            "id": 100710,
            "city": "营口市",
            "pinyin": "yingkoushi"
        }, {
            "id": 100711,
            "city": "盘锦市",
            "pinyin": "panjinshi"
        }, {
            "id": 100712,
            "city": "锦州市",
            "pinyin": "jinzhoushi"
        }, {
            "id": 100713,
            "city": "葫芦岛市",
            "pinyin": "huludaoshi"
        }, {
            "id": 100080,
            "city": "长春市",
            "pinyin": "changchunshi"
        }, {
            "id": 100081,
            "city": "白城市",
            "pinyin": "baichengshi"
        }, {
            "id": 100082,
            "city": "松原市",
            "pinyin": "songyuanshi"
        }, {
            "id": 100083,
            "city": "吉林市",
            "pinyin": "jilinshi"
        }, {
            "id": 100084,
            "city": "四平市",
            "pinyin": "sipingshi"
        }, {
            "id": 100085,
            "city": "辽源市",
            "pinyin": "liaoyuanshi"
        }, {
            "id": 100086,
            "city": "通化市",
            "pinyin": "tonghuashi"
        }, {
            "id": 100087,
            "city": "白山市",
            "pinyin": "baishanshi"
        }, {
            "id": 100088,
            "city": "延边州",
            "pinyin": "yanbianzhou"
        }, {
            "id": 100090,
            "city": "哈尔滨市",
            "pinyin": "haerbinshi"
        }, {
            "id": 100091,
            "city": "齐齐哈尔市",
            "pinyin": "qiqihaershi"
        }, {
            "id": 100092,
            "city": "七台河市",
            "pinyin": "qitaiheshi"
        }, {
            "id": 100093,
            "city": "黑河市",
            "pinyin": "heiheshi"
        }, {
            "id": 100094,
            "city": "大庆市",
            "pinyin": "daqingshi"
        }, {
            "id": 100095,
            "city": "鹤岗市",
            "pinyin": "hegangshi"
        }, {
            "id": 100096,
            "city": "伊春市",
            "pinyin": "yichunshi"
        }, {
            "id": 100097,
            "city": "佳木斯市",
            "pinyin": "jiamusishi"
        }, {
            "id": 100098,
            "city": "双鸭山市",
            "pinyin": "shuangyashanshi"
        }, {
            "id": 100099,
            "city": "鸡西市",
            "pinyin": "jixishi"
        }, {
            "id": 100910,
            "city": "牡丹江市",
            "pinyin": "mudanjiangshi"
        }, {
            "id": 100911,
            "city": "绥化市",
            "pinyin": "suihuashi"
        }, {
            "id": 100912,
            "city": "大兴安岭地区",
            "pinyin": "daxinganlingdiqu"
        }, {
            "id": 100100,
            "city": "南京市",
            "pinyin": "nanjingshi"
        }, {
            "id": 100101,
            "city": "徐州市",
            "pinyin": "xuzhoushi"
        }, {
            "id": 100102,
            "city": "连云港市",
            "pinyin": "lianyungangshi"
        }, {
            "id": 100103,
            "city": "宿迁市",
            "pinyin": "suqianshi"
        }, {
            "id": 100104,
            "city": "淮安市",
            "pinyin": "huaianshi"
        }, {
            "id": 100105,
            "city": "盐城市",
            "pinyin": "yanchengshi"
        }, {
            "id": 100106,
            "city": "扬州市",
            "pinyin": "yangzhoushi"
        }, {
            "id": 100107,
            "city": "泰州市",
            "pinyin": "taizhoushi"
        }, {
            "id": 100108,
            "city": "南通市",
            "pinyin": "nantongshi"
        }, {
            "id": 100109,
            "city": "镇江市",
            "pinyin": "zhenjiangshi"
        }, {
            "id": 101010,
            "city": "常州市",
            "pinyin": "changzhoushi"
        }, {
            "id": 101011,
            "city": "无锡市",
            "pinyin": "wuxishi"
        }, {
            "id": 101012,
            "city": "苏州市",
            "pinyin": "suzhoushi"
        }, {
            "id": 100110,
            "city": "杭州市",
            "pinyin": "hangzhoushi"
        }, {
            "id": 100111,
            "city": "湖州市",
            "pinyin": "huzhoushi"
        }, {
            "id": 100112,
            "city": "嘉兴市",
            "pinyin": "jiaxingshi"
        }, {
            "id": 100113,
            "city": "舟山市",
            "pinyin": "zhoushanshi"
        }, {
            "id": 100114,
            "city": "宁波市",
            "pinyin": "ningboshi"
        }, {
            "id": 100115,
            "city": "绍兴市",
            "pinyin": "shaoxingshi"
        }, {
            "id": 100116,
            "city": "衢州市",
            "pinyin": "quzhoushi"
        }, {
            "id": 100117,
            "city": "金华市",
            "pinyin": "jinhuashi"
        }, {
            "id": 100118,
            "city": "台州市",
            "pinyin": "taizhoushi"
        }, {
            "id": 100119,
            "city": "温州市",
            "pinyin": "wenzhoushi"
        }, {
            "id": 101110,
            "city": "丽水市",
            "pinyin": "lishuishi"
        }, {
            "id": 100120,
            "city": "合肥市",
            "pinyin": "hefeishi"
        }, {
            "id": 100121,
            "city": "宿州市",
            "pinyin": "suzhoushi"
        }, {
            "id": 100122,
            "city": "淮北市",
            "pinyin": "huaibeishi"
        }, {
            "id": 100123,
            "city": "亳州市",
            "pinyin": "bozhoushi"
        }, {
            "id": 100124,
            "city": "阜阳市",
            "pinyin": "fuyangshi"
        }, {
            "id": 100125,
            "city": "蚌埠市",
            "pinyin": "bengbushi"
        }, {
            "id": 100126,
            "city": "淮南市",
            "pinyin": "huainanshi"
        }, {
            "id": 100127,
            "city": "滁州市",
            "pinyin": "chuzhoushi"
        }, {
            "id": 100128,
            "city": "马鞍山市",
            "pinyin": "maanshanshi"
        }, {
            "id": 100129,
            "city": "芜湖市",
            "pinyin": "wuhushi"
        }, {
            "id": 101210,
            "city": "铜陵市",
            "pinyin": "tonglingshi"
        }, {
            "id": 101211,
            "city": "安庆市",
            "pinyin": "anqingshi"
        }, {
            "id": 101212,
            "city": "黄山市",
            "pinyin": "huangshanshi"
        }, {
            "id": 101213,
            "city": "六安市",
            "pinyin": "liuanshi"
        }, {
            "id": 101214,
            "city": "巢湖市",
            "pinyin": "chaohushi"
        }, {
            "id": 101215,
            "city": "池州市",
            "pinyin": "chizhoushi"
        }, {
            "id": 101216,
            "city": "宣城市",
            "pinyin": "xuanchengshi"
        }, {
            "id": 100130,
            "city": "福州市",
            "pinyin": "fuzhoushi"
        }, {
            "id": 100131,
            "city": "南平市",
            "pinyin": "nanpingshi"
        }, {
            "id": 100132,
            "city": "莆田市",
            "pinyin": "putianshi"
        }, {
            "id": 100133,
            "city": "三明市",
            "pinyin": "sanmingshi"
        }, {
            "id": 100134,
            "city": "泉州市",
            "pinyin": "quanzhoushi"
        }, {
            "id": 100135,
            "city": "厦门市",
            "pinyin": "xiamenshi"
        }, {
            "id": 100136,
            "city": "漳州市",
            "pinyin": "zhangzhoushi"
        }, {
            "id": 100137,
            "city": "龙岩市",
            "pinyin": "longyanshi"
        }, {
            "id": 100138,
            "city": "宁德市",
            "pinyin": "ningdeshi"
        }, {
            "id": 100140,
            "city": "南昌市",
            "pinyin": "nanchangshi"
        }, {
            "id": 100141,
            "city": "九江市",
            "pinyin": "jiujiangshi"
        }, {
            "id": 100142,
            "city": "景德镇市",
            "pinyin": "jingdezhenshi"
        }, {
            "id": 100143,
            "city": "鹰潭市",
            "pinyin": "yingtanshi"
        }, {
            "id": 100144,
            "city": "新余市",
            "pinyin": "xinyushi"
        }, {
            "id": 100145,
            "city": "萍乡市",
            "pinyin": "pingxiangshi"
        }, {
            "id": 100146,
            "city": "赣州市",
            "pinyin": "ganzhoushi"
        }, {
            "id": 100147,
            "city": "上饶市",
            "pinyin": "shangraoshi"
        }, {
            "id": 100148,
            "city": "抚州市",
            "pinyin": "fuzhoushi"
        }, {
            "id": 100149,
            "city": "宜春市",
            "pinyin": "yichunshi"
        }, {
            "id": 101410,
            "city": "吉安市",
            "pinyin": "jianshi"
        }, {
            "id": 100150,
            "city": "济南市",
            "pinyin": "jinanshi"
        }, {
            "id": 100151,
            "city": "青岛市",
            "pinyin": "qingdaoshi"
        }, {
            "id": 100152,
            "city": "聊城市",
            "pinyin": "liaochengshi"
        }, {
            "id": 100153,
            "city": "德州市",
            "pinyin": "dezhoushi"
        }, {
            "id": 100154,
            "city": "东营市",
            "pinyin": "dongyingshi"
        }, {
            "id": 100155,
            "city": "淄博市",
            "pinyin": "ziboshi"
        }, {
            "id": 100156,
            "city": "潍坊市",
            "pinyin": "weifangshi"
        }, {
            "id": 100157,
            "city": "烟台市",
            "pinyin": "yantaishi"
        }, {
            "id": 100158,
            "city": "威海市",
            "pinyin": "weihaishi"
        }, {
            "id": 100159,
            "city": "日照市",
            "pinyin": "rizhaoshi"
        }, {
            "id": 101510,
            "city": "临沂市",
            "pinyin": "linyishi"
        }, {
            "id": 101511,
            "city": "枣庄市",
            "pinyin": "zaozhuangshi"
        }, {
            "id": 101512,
            "city": "济宁市",
            "pinyin": "jiningshi"
        }, {
            "id": 101513,
            "city": "泰安市",
            "pinyin": "taianshi"
        }, {
            "id": 101514,
            "city": "莱芜市",
            "pinyin": "laiwushi"
        }, {
            "id": 101515,
            "city": "滨州市",
            "pinyin": "binzhoushi"
        }, {
            "id": 101516,
            "city": "菏泽市",
            "pinyin": "hezeshi"
        }, {
            "id": 100160,
            "city": "郑州市",
            "pinyin": "zhengzhoushi"
        }, {
            "id": 100161,
            "city": "开封市",
            "pinyin": "kaifengshi"
        }, {
            "id": 100162,
            "city": "三门峡市",
            "pinyin": "sanmenxiashi"
        }, {
            "id": 100163,
            "city": "洛阳市",
            "pinyin": "luoyangshi"
        }, {
            "id": 100164,
            "city": "焦作市",
            "pinyin": "jiaozuoshi"
        }, {
            "id": 100165,
            "city": "新乡市",
            "pinyin": "xinxiangshi"
        }, {
            "id": 100166,
            "city": "鹤壁市",
            "pinyin": "hebishi"
        }, {
            "id": 100167,
            "city": "安阳市",
            "pinyin": "anyangshi"
        }, {
            "id": 100168,
            "city": "濮阳市",
            "pinyin": "puyangshi"
        }, {
            "id": 100169,
            "city": "商丘市",
            "pinyin": "shangqiushi"
        }, {
            "id": 101610,
            "city": "许昌市",
            "pinyin": "xuchangshi"
        }, {
            "id": 101611,
            "city": "漯河市",
            "pinyin": "luoheshi"
        }, {
            "id": 101612,
            "city": "平顶山市",
            "pinyin": "pingdingshanshi"
        }, {
            "id": 101613,
            "city": "南阳市",
            "pinyin": "nanyangshi"
        }, {
            "id": 101614,
            "city": "信阳市",
            "pinyin": "xinyangshi"
        }, {
            "id": 101615,
            "city": "周口市",
            "pinyin": "zhoukoushi"
        }, {
            "id": 101616,
            "city": "驻马店市",
            "pinyin": "zhumadianshi"
        }, {
            "id": 100170,
            "city": "武汉市",
            "pinyin": "wuhanshi"
        }, {
            "id": 100171,
            "city": "十堰市",
            "pinyin": "shiyanshi"
        }, {
            "id": 100172,
            "city": "襄樊市",
            "pinyin": "xiangfanshi"
        }, {
            "id": 100173,
            "city": "荆门市",
            "pinyin": "jingmenshi"
        }, {
            "id": 100174,
            "city": "孝感市",
            "pinyin": "xiaoganshi"
        }, {
            "id": 100175,
            "city": "黄冈市",
            "pinyin": "huanggangshi"
        }, {
            "id": 100176,
            "city": "鄂州市",
            "pinyin": "ezhoushi"
        }, {
            "id": 100177,
            "city": "黄石市",
            "pinyin": "huangshishi"
        }, {
            "id": 100178,
            "city": "咸宁市",
            "pinyin": "xianningshi"
        }, {
            "id": 100179,
            "city": "荆州市",
            "pinyin": "jingzhoushi"
        }, {
            "id": 101710,
            "city": "宜昌市",
            "pinyin": "yichangshi"
        }, {
            "id": 101711,
            "city": "随州市",
            "pinyin": "suizhoushi"
        }, {
            "id": 101712,
            "city": "省直辖县级行政单位",
            "pinyin": "shengzhixiaxianjixingzhengdanwei"
        }, {
            "id": 101713,
            "city": "恩施州",
            "pinyin": "enshizhou"
        }, {
            "id": 100180,
            "city": "长沙市",
            "pinyin": "changshashi"
        }, {
            "id": 100181,
            "city": "张家界市",
            "pinyin": "zhangjiajieshi"
        }, {
            "id": 100182,
            "city": "常德市",
            "pinyin": "changdeshi"
        }, {
            "id": 100183,
            "city": "益阳市",
            "pinyin": "yiyangshi"
        }, {
            "id": 100184,
            "city": "岳阳市",
            "pinyin": "yueyangshi"
        }, {
            "id": 100185,
            "city": "株洲市",
            "pinyin": "zhuzhoushi"
        }, {
            "id": 100186,
            "city": "湘潭市",
            "pinyin": "xiangtanshi"
        }, {
            "id": 100187,
            "city": "衡阳市",
            "pinyin": "hengyangshi"
        }, {
            "id": 100188,
            "city": "郴州市",
            "pinyin": "chenzhoushi"
        }, {
            "id": 100189,
            "city": "永州市",
            "pinyin": "yongzhoushi"
        }, {
            "id": 101810,
            "city": "邵阳市",
            "pinyin": "shaoyangshi"
        }, {
            "id": 101811,
            "city": "怀化市",
            "pinyin": "huaihuashi"
        }, {
            "id": 101812,
            "city": "娄底市",
            "pinyin": "loudishi"
        }, {
            "id": 101813,
            "city": "湘西州",
            "pinyin": "xiangxizhou"
        }, {
            "id": 100190,
            "city": "广州市",
            "pinyin": "guangzhoushi"
        }, {
            "id": 100191,
            "city": "深圳市",
            "pinyin": "shenzhenshi"
        }, {
            "id": 100192,
            "city": "清远市",
            "pinyin": "qingyuanshi"
        }, {
            "id": 100193,
            "city": "韶关市",
            "pinyin": "shaoguanshi"
        }, {
            "id": 100194,
            "city": "河源市",
            "pinyin": "heyuanshi"
        }, {
            "id": 100195,
            "city": "梅州市",
            "pinyin": "meizhoushi"
        }, {
            "id": 100196,
            "city": "潮州市",
            "pinyin": "chaozhoushi"
        }, {
            "id": 100197,
            "city": "汕头市",
            "pinyin": "shantoushi"
        }, {
            "id": 100198,
            "city": "揭阳市",
            "pinyin": "jieyangshi"
        }, {
            "id": 100199,
            "city": "汕尾市",
            "pinyin": "shanweishi"
        }, {
            "id": 101910,
            "city": "惠州市",
            "pinyin": "huizhoushi"
        }, {
            "id": 101911,
            "city": "东莞市",
            "pinyin": "dongguanshi"
        }, {
            "id": 101912,
            "city": "珠海市",
            "pinyin": "zhuhaishi"
        }, {
            "id": 101913,
            "city": "中山市",
            "pinyin": "zhongshanshi"
        }, {
            "id": 101914,
            "city": "江门市",
            "pinyin": "jiangmenshi"
        }, {
            "id": 101915,
            "city": "佛山市",
            "pinyin": "foshanshi"
        }, {
            "id": 101916,
            "city": "肇庆市",
            "pinyin": "zhaoqingshi"
        }, {
            "id": 101917,
            "city": "云浮市",
            "pinyin": "yunfushi"
        }, {
            "id": 101918,
            "city": "阳江市",
            "pinyin": "yangjiangshi"
        }, {
            "id": 101919,
            "city": "茂名市",
            "pinyin": "maomingshi"
        }, {
            "id": 101920,
            "city": "湛江市",
            "pinyin": "zhanjiangshi"
        }, {
            "id": 100200,
            "city": "南宁市",
            "pinyin": "nanningshi"
        }, {
            "id": 100201,
            "city": "桂林市",
            "pinyin": "guilinshi"
        }, {
            "id": 100202,
            "city": "柳州市",
            "pinyin": "liuzhoushi"
        }, {
            "id": 100203,
            "city": "梧州市",
            "pinyin": "wuzhoushi"
        }, {
            "id": 100204,
            "city": "贵港市",
            "pinyin": "guigangshi"
        }, {
            "id": 100205,
            "city": "玉林市",
            "pinyin": "yulinshi"
        }, {
            "id": 100206,
            "city": "钦州市",
            "pinyin": "qinzhoushi"
        }, {
            "id": 100207,
            "city": "北海市",
            "pinyin": "beihaishi"
        }, {
            "id": 100208,
            "city": "防城港市",
            "pinyin": "fangchenggangshi"
        }, {
            "id": 100209,
            "city": "崇左市",
            "pinyin": "chongzuoshi"
        }, {
            "id": 102010,
            "city": "百色市",
            "pinyin": "baiseshi"
        }, {
            "id": 102011,
            "city": "河池市",
            "pinyin": "hechishi"
        }, {
            "id": 102012,
            "city": "来宾市",
            "pinyin": "laibinshi"
        }, {
            "id": 102013,
            "city": "贺州市",
            "pinyin": "hezhoushi"
        }, {
            "id": 100210,
            "city": "海口市",
            "pinyin": "haikoushi"
        }, {
            "id": 100211,
            "city": "三亚市",
            "pinyin": "sanyashi"
        }, {
            "id": 100212,
            "city": "省直辖行政单位",
            "pinyin": "shengzhixiaxingzhengdanwei"
        }, {
            "id": 100220,
            "city": "成都市",
            "pinyin": "chengdushi"
        }, {
            "id": 100221,
            "city": "广元市",
            "pinyin": "guangyuanshi"
        }, {
            "id": 100222,
            "city": "绵阳市",
            "pinyin": "mianyangshi"
        }, {
            "id": 100223,
            "city": "德阳市",
            "pinyin": "deyangshi"
        }, {
            "id": 100224,
            "city": "南充市",
            "pinyin": "nanchongshi"
        }, {
            "id": 100225,
            "city": "广安市",
            "pinyin": "guanganshi"
        }, {
            "id": 100226,
            "city": "遂宁市",
            "pinyin": "suiningshi"
        }, {
            "id": 100227,
            "city": "内江市",
            "pinyin": "neijiangshi"
        }, {
            "id": 100228,
            "city": "乐山市",
            "pinyin": "leshanshi"
        }, {
            "id": 100229,
            "city": "自贡市",
            "pinyin": "zigongshi"
        }, {
            "id": 102210,
            "city": "泸州市",
            "pinyin": "luzhoushi"
        }, {
            "id": 102211,
            "city": "宜宾市",
            "pinyin": "yibinshi"
        }, {
            "id": 102212,
            "city": "攀枝花市",
            "pinyin": "panzhihuashi"
        }, {
            "id": 102213,
            "city": "巴中市",
            "pinyin": "bazhongshi"
        }, {
            "id": 102214,
            "city": "达州市",
            "pinyin": "dazhoushi"
        }, {
            "id": 102215,
            "city": "资阳市",
            "pinyin": "ziyangshi"
        }, {
            "id": 102216,
            "city": "眉山市",
            "pinyin": "meishanshi"
        }, {
            "id": 102217,
            "city": "雅安市",
            "pinyin": "yaanshi"
        }, {
            "id": 102218,
            "city": "阿坝州",
            "pinyin": "abazhou"
        }, {
            "id": 102219,
            "city": "甘孜州",
            "pinyin": "ganzizhou"
        }, {
            "id": 102220,
            "city": "凉山州",
            "pinyin": "liangshanzhou"
        }, {
            "id": 100230,
            "city": "贵阳市",
            "pinyin": "guiyangshi"
        }, {
            "id": 100231,
            "city": "六盘水市",
            "pinyin": "liupanshuishi"
        }, {
            "id": 100232,
            "city": "遵义市",
            "pinyin": "zunyishi"
        }, {
            "id": 100233,
            "city": "安顺市",
            "pinyin": "anshunshi"
        }, {
            "id": 100234,
            "city": "毕节地区",
            "pinyin": "bijiediqu"
        }, {
            "id": 100235,
            "city": "铜仁地区",
            "pinyin": "tongrendiqu"
        }, {
            "id": 100236,
            "city": "黔东南州",
            "pinyin": "qiandongnanzhou"
        }, {
            "id": 100237,
            "city": "黔南州",
            "pinyin": "qiannanzhou"
        }, {
            "id": 100238,
            "city": "黔西南州",
            "pinyin": "qianxinanzhou"
        }, {
            "id": 100240,
            "city": "昆明市",
            "pinyin": "kunmingshi"
        }, {
            "id": 100241,
            "city": "曲靖市",
            "pinyin": "qujingshi"
        }, {
            "id": 100242,
            "city": "玉溪市",
            "pinyin": "yuxishi"
        }, {
            "id": 100243,
            "city": "保山市",
            "pinyin": "baoshanshi"
        }, {
            "id": 100244,
            "city": "昭通市",
            "pinyin": "zhaotongshi"
        }, {
            "id": 100245,
            "city": "丽江市",
            "pinyin": "lijiangshi"
        }, {
            "id": 100246,
            "city": "思茅市",
            "pinyin": "simaoshi"
        }, {
            "id": 100247,
            "city": "临沧市",
            "pinyin": "lincangshi"
        }, {
            "id": 100248,
            "city": "德宏州",
            "pinyin": "dehongzhou"
        }, {
            "id": 100249,
            "city": "怒江州",
            "pinyin": "nujiangzhou"
        }, {
            "id": 102410,
            "city": "迪庆州",
            "pinyin": "diqingzhou"
        }, {
            "id": 102411,
            "city": "大理州",
            "pinyin": "dalizhou"
        }, {
            "id": 102412,
            "city": "楚雄州",
            "pinyin": "chuxiongzhou"
        }, {
            "id": 102413,
            "city": "红河州",
            "pinyin": "honghezhou"
        }, {
            "id": 102414,
            "city": "文山州",
            "pinyin": "wenshanzhou"
        }, {
            "id": 102415,
            "city": "西双版纳州",
            "pinyin": "xishuangbannazhou"
        }, {
            "id": 100250,
            "city": "拉萨市",
            "pinyin": "lasashi"
        }, {
            "id": 100251,
            "city": "那曲地区",
            "pinyin": "naqudiqu"
        }, {
            "id": 100252,
            "city": "昌都地区",
            "pinyin": "changdudiqu"
        }, {
            "id": 100253,
            "city": "林芝地区",
            "pinyin": "linzhidiqu"
        }, {
            "id": 100254,
            "city": "山南地区",
            "pinyin": "shannandiqu"
        }, {
            "id": 100255,
            "city": "日喀则地区",
            "pinyin": "rikazediqu"
        }, {
            "id": 100256,
            "city": "阿里地区",
            "pinyin": "alidiqu"
        }, {
            "id": 100260,
            "city": "西安市",
            "pinyin": "xianshi"
        }, {
            "id": 100261,
            "city": "延安市",
            "pinyin": "yananshi"
        }, {
            "id": 100262,
            "city": "铜川市",
            "pinyin": "tongchuanshi"
        }, {
            "id": 100263,
            "city": "渭南市",
            "pinyin": "weinanshi"
        }, {
            "id": 100264,
            "city": "咸阳市",
            "pinyin": "xianyangshi"
        }, {
            "id": 100265,
            "city": "宝鸡市",
            "pinyin": "baojishi"
        }, {
            "id": 100266,
            "city": "汉中市",
            "pinyin": "hanzhongshi"
        }, {
            "id": 100267,
            "city": "榆林市",
            "pinyin": "yulinshi"
        }, {
            "id": 100268,
            "city": "安康市",
            "pinyin": "ankangshi"
        }, {
            "id": 100269,
            "city": "商洛市",
            "pinyin": "shangluoshi"
        }, {
            "id": 100270,
            "city": "兰州市",
            "pinyin": "lanzhoushi"
        }, {
            "id": 100271,
            "city": "嘉峪关市",
            "pinyin": "jiayuguanshi"
        }, {
            "id": 100272,
            "city": "白银市",
            "pinyin": "baiyinshi"
        }, {
            "id": 100273,
            "city": "天水市",
            "pinyin": "tianshuishi"
        }, {
            "id": 100274,
            "city": "武威市",
            "pinyin": "wuweishi"
        }, {
            "id": 100275,
            "city": "酒泉市",
            "pinyin": "jiuquanshi"
        }, {
            "id": 100276,
            "city": "张掖市",
            "pinyin": "zhangyeshi"
        }, {
            "id": 100277,
            "city": "庆阳市",
            "pinyin": "qingyangshi"
        }, {
            "id": 100278,
            "city": "平凉市",
            "pinyin": "pingliangshi"
        }, {
            "id": 100279,
            "city": "定西市",
            "pinyin": "dingxishi"
        }, {
            "id": 102710,
            "city": "陇南市",
            "pinyin": "longnanshi"
        }, {
            "id": 102711,
            "city": "临夏州",
            "pinyin": "linxiazhou"
        }, {
            "id": 102712,
            "city": "甘南州",
            "pinyin": "gannanzhou"
        }, {
            "id": 100280,
            "city": "西宁市",
            "pinyin": "xiningshi"
        }, {
            "id": 100281,
            "city": "海东地区",
            "pinyin": "haidongdiqu"
        }, {
            "id": 100282,
            "city": "海北州",
            "pinyin": "haibeizhou"
        }, {
            "id": 100283,
            "city": "海南州",
            "pinyin": "hainanzhou"
        }, {
            "id": 100284,
            "city": "黄南州",
            "pinyin": "huangnanzhou"
        }, {
            "id": 100285,
            "city": "果洛州",
            "pinyin": "guoluozhou"
        }, {
            "id": 100286,
            "city": "玉树州",
            "pinyin": "yushuzhou"
        }, {
            "id": 100287,
            "city": "海西州",
            "pinyin": "haixizhou"
        }, {
            "id": 100290,
            "city": "银川市",
            "pinyin": "yinchuanshi"
        }, {
            "id": 100291,
            "city": "石嘴山市",
            "pinyin": "shizuishanshi"
        }, {
            "id": 100292,
            "city": "吴忠市",
            "pinyin": "wuzhongshi"
        }, {
            "id": 100293,
            "city": "固原市",
            "pinyin": "guyuanshi"
        }, {
            "id": 100294,
            "city": "中卫市",
            "pinyin": "zhongweishi"
        }, {
            "id": 100300,
            "city": "乌鲁木齐市",
            "pinyin": "wulumuqishi"
        }, {
            "id": 100301,
            "city": "克拉玛依市",
            "pinyin": "kelamayishi"
        }, {
            "id": 100302,
            "city": "自治区直辖县级行政单位",
            "pinyin": "zizhiquzhixiaxianjixingzhengdanwei"
        }, {
            "id": 100303,
            "city": "喀什地区",
            "pinyin": "kashendiqu"
        }, {
            "id": 100304,
            "city": "阿克苏地区",
            "pinyin": "akesudiqu"
        }, {
            "id": 100305,
            "city": "和田地区",
            "pinyin": "hetiandiqu"
        }, {
            "id": 100306,
            "city": "吐鲁番地区",
            "pinyin": "tulufandiqu"
        }, {
            "id": 100307,
            "city": "哈密地区",
            "pinyin": "hamidiqu"
        }, {
            "id": 100308,
            "city": "克孜勒苏柯州",
            "pinyin": "kezilesukezhou"
        }, {
            "id": 100309,
            "city": "博尔塔拉州",
            "pinyin": "boertalazhou"
        }, {
            "id": 103010,
            "city": "昌吉州",
            "pinyin": "changjizhou"
        }, {
            "id": 103011,
            "city": "巴音郭楞州",
            "pinyin": "bayinguolengzhou"
        }, {
            "id": 103012,
            "city": "伊犁州",
            "pinyin": "yilizhou"
        }, {
            "id": 103013,
            "city": "塔城地区",
            "pinyin": "tachengdiqu"
        }, {
            "id": 103014,
            "city": "阿勒泰地区",
            "pinyin": "aletaidiqu"
        }, {
            "id": 100310,
            "city": "香港特别行政区",
            "pinyin": "xianggangtebiexingzhengqu"
        }, {
            "id": 100320,
            "city": "澳门特别行政区",
            "pinyin": "aomentebiexingzhengqu"
        }, {
            "id": 100330,
            "city": "台北",
            "pinyin": "taibei"
        }, {
            "id": 100331,
            "city": "高雄",
            "pinyin": "gaoxiong"
        }, {
            "id": 100332,
            "city": "台中",
            "pinyin": "taizhong"
        }, {
            "id": 100333,
            "city": "花莲",
            "pinyin": "hualian"
        }, {
            "id": 100334,
            "city": "基隆",
            "pinyin": "jilong"
        }, {
            "id": 100335,
            "city": "嘉义",
            "pinyin": "jiayi"
        }, {
            "id": 100336,
            "city": "金门",
            "pinyin": "jinmen"
        }, {
            "id": 100337,
            "city": "连江",
            "pinyin": "lianjiang"
        }, {
            "id": 100338,
            "city": "苗栗",
            "pinyin": "miaoli"
        }, {
            "id": 100339,
            "city": "南投",
            "pinyin": "nantou"
        }, {
            "id": 103310,
            "city": "澎湖",
            "pinyin": "penghu"
        }, {
            "id": 103311,
            "city": "屏东",
            "pinyin": "pingdong"
        }, {
            "id": 103312,
            "city": "台东",
            "pinyin": "taidong"
        }, {
            "id": 103313,
            "city": "台南",
            "pinyin": "tainan"
        }, {
            "id": 103314,
            "city": "桃园",
            "pinyin": "taoyuan"
        }, {
            "id": 103315,
            "city": "新竹",
            "pinyin": "xinzhu"
        }, {
            "id": 103316,
            "city": "宜兰",
            "pinyin": "yilan"
        }, {
            "id": 103317,
            "city": "云林",
            "pinyin": "yunlin"
        }, {
            "id": 103318,
            "city": "彰化",
            "pinyin": "zhanghua"
        }]
    },
    letterCitys: [{
        key: "A",
        val: ["阿拉善盟", "鞍山市", "安庆市", "安阳市", "阿坝州", "安顺市", "阿里地区", "安康市", "阿克苏地区", "阿勒泰地区", "澳门特别行政区"]
    }, {
        key: "B",
        val: ["北京市", "保定市", "包头市", "巴彦淖尔市", "本溪市", "白城市", "白山市", "亳州市", "蚌埠市", "滨州市", "北海市", "百色市", "巴中市", "毕节地区", "保山市", "宝鸡市", "白银市", "博尔塔拉州", "巴音郭楞州"]
    }, {
        key: "C",
        val: ["重庆市", "承德市", "沧州市", "长治市", "赤峰市", "朝阳市", "长春市", "常州市", "滁州市", "巢湖市", "池州市", "长沙市", "常德市", "郴州市", "潮州市", "崇左市", "成都市", "楚雄州", "昌都地区", "昌吉州"]
    }, {
        key: "D",
        val: ["大同市", "丹东市", "大连市", "大庆市", "大兴安岭地区", "德州市", "东营市", "东莞市", "德阳市", "达州市", "德宏州", "迪庆州", "大理州", "定西市"]
    }, {
        key: "E",
        val: ["鄂尔多斯市", "鄂州市", "恩施州"]
    }, {
        key: "F",
        val: ["阜新市", "抚顺市", "阜阳市", "福州市", "抚州市", "佛山市", "防城港市"]
    }, {
        key: "G",
        val: ["赣州市", "广州市", "桂林市", "贵港市", "广元市", "广安市", "甘孜州", "贵阳市", "甘南州", "果洛州", "固原市", "高雄"]
    }, {
        key: "H",
        val: ["衡水市", "邯郸市", "呼和浩特市", "呼伦贝尔市", "葫芦岛市", "哈尔滨市", "黑河市", "鹤岗市", "淮安市", "杭州市", "湖州市", "合肥市", "淮北市", "淮南市", "黄山市", "菏泽市", "鹤壁市", "黄冈市", "黄石市", "衡阳市", "怀化市", "河源市", "惠州市", "河池市", "贺州市", "海口市", "红河州", "汉中市", "海东地区", "海北州", "海南州", "黄南州", "海西州", "和田地区", "哈密地区", "花莲"]
    }, {
        key: "J",
        val: ["晋城市", "晋中市", "锦州市", "吉林市", "佳木斯市", "鸡西市", "嘉兴市", "金华市", "九江市", "景德镇市", "吉安市", "济南市", "济宁市", "焦作市", "荆门市", "荆州市", "揭阳市", "江门市", "嘉峪关市", "酒泉市", "基隆", "嘉义", "金门"]
    }, {
        key: "K",
        val: ["开封市", "昆明市", "克拉玛依市", "喀什地区", "克孜勒苏柯州"]
    }, {
        key: "L",
        val: ["廊坊市", "临汾市", "吕梁市", "辽阳市", "辽源市", "连云港市", "丽水市", "六安市", "龙岩市", "聊城市", "临沂市", "莱芜市", "洛阳市", "漯河市", "娄底市", "柳州市", "来宾市", "乐山市", "泸州市", "凉山州", "六盘水市", "丽江市", "临沧市", "拉萨市", "林芝地区", "兰州市", "陇南市", "临夏州", "连江"]
    }, {
        key: "M",
        val: ["牡丹江市", "马鞍山市", "梅州市", "茂名市", "绵阳市", "眉山市", "苗栗"]
    }, {
        key: "N",
        val: ["南京市", "南通市", "宁波市", "南平市", "宁德市", "南昌市", "南阳市", "南宁市", "南充市", "内江市", "怒江州", "那曲地区", "南投"]
    }, {
        key: "P",
        val: ["盘锦市", "莆田市", "萍乡市", "濮阳市", "平顶山市", "攀枝花市", "平凉市", "澎湖", "屏东"]
    }, {
        key: "Q",
        val: ["秦皇岛市", "齐齐哈尔市", "七台河市", "衢州市", "泉州市", "青岛市", "清远市", "钦州市", "黔东南州", "黔南州", "黔西南州", "曲靖市", "庆阳市"]
    }, {
        key: "R",
        val: ["日照市", "日喀则地区"]
    }, {
        key: "S",
        val: ["上海市", "石家庄市", "朔州市", "沈阳市", "松原市", "四平市", "双鸭山市", "绥化市", "宿迁市", "苏州市", "绍兴市", "宿州市", "三明市", "上饶市", "三门峡市", "商丘市", "十堰市", "随州市", "省直辖县级行政单位", "邵阳市", "深圳市", "韶关市", "汕头市", "汕尾市", "三亚市", "省直辖行政单位", "遂宁市", "思茅市", "山南地区", "商洛市", "石嘴山市"]
    }, {
        key: "T",
        val: ["天津市", "唐山市", "太原市", "通辽市", "铁岭市", "通化市", "泰州市", "台州市", "铜陵市", "泰安市", "铜仁地区", "铜川市", "天水市", "吐鲁番地区", "塔城地区", "台北", "台中", "台东", "台南", "桃园"]
    }, {
        key: "W",
        val: ["乌海市", "乌兰察布市", "无锡市", "温州市", "芜湖市", "潍坊市", "威海市", "武汉市", "梧州市", "文山州", "渭南市", "武威市", "吴忠市", "乌鲁木齐市"]
    }, {
        key: "X",
        val: ["邢台市", "忻州市", "兴安盟", "锡林郭勒盟", "徐州市", "宣城市", "厦门市", "新余市", "新乡市", "许昌市", "信阳市", "襄樊市", "孝感市", "咸宁市", "湘潭市", "湘西州", "西双版纳州", "西安市", "咸阳市", "西宁市", "香港特别行政区", "新竹"]
    }, {
        key: "Y",
        val: ["阳泉市", "运城市", "营口市", "延边州", "伊春市", "盐城市", "扬州市", "鹰潭市", "宜春市", "烟台市", "宜昌市", "益阳市", "岳阳市", "永州市", "云浮市", "阳江市", "玉林市", "宜宾市", "雅安市", "玉溪市", "延安市", "榆林市", "玉树州", "银川市", "伊犁州", "宜兰", "云林"]
    }, {
        key: "Z",
        val: ["张家口市", "镇江市", "舟山市", "漳州市", "淄博市", "枣庄市", "郑州市", "周口市", "驻马店市", "张家界市", "株洲市", "珠海市", "中山市", "肇庆市", "湛江市", "自贡市", "资阳市", "遵义市", "昭通市", "张掖市", "中卫市", "自治区直辖县级行政单位", "彰化"]
    }]
};

config.prototype.constructor = config;
module.exports = new config();